"""add index on judge_records2.language

Revision ID: 578abe41c3f3
Revises: 8ceb49ae1438
Create Date: 2023-11-02 22:22:33.442519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '578abe41c3f3'
down_revision: Union[str, None] = '8ceb49ae1438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('judge_records2', 'language',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_judge_records2_language'), 'judge_records2', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judge_records2_language'), table_name='judge_records2')
    op.alter_column('judge_records2', 'language',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
