"""use argon2 for password hashing

Revision ID: 02d53b659c7c
Revises: 578abe41c3f3
Create Date: 2023-12-17 15:16:33.891831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02d53b659c7c'
down_revision: Union[str, None] = '578abe41c3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE User SET Password = CONCAT('$SHA512$', Salt, '$', Password);")
    # op.drop_column('User', 'Salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    raise Exception('This migration could not be reversed automatically.')
    # op.add_column('User', sa.Column('Salt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
