"""add column preference to table User

Revision ID: f9296a662870
Revises: 8ceb49ae1438
Create Date: 2023-10-13 22:33:20.409780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9296a662870'
down_revision: Union[str, None] = '8ceb49ae1438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Preference', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'Preference')
    # ### end Alembic commands ###
