"""problem: remove limits, add plan_summary

Revision ID: 5f5ce14c214d
Revises: 6d43b30e1d3d
Create Date: 2024-12-28 20:21:30.281527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f5ce14c214d'
down_revision: Union[str, None] = '6d43b30e1d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('plan_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('problem', 'limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('problem', 'plan_summary')
    # ### end Alembic commands ###
