"""add rank all on contest

Revision ID: 2639b12746e6
Revises: 0245b59b53b9
Create Date: 2024-02-02 16:00:42.809979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2639b12746e6'
down_revision: Union[str, None] = '0245b59b53b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('rank_all_users', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('contest', 'rank_all_users', server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'rank_all_users')
    # ### end Alembic commands ###
