"""change student_id from int to text

Revision ID: 4a8c8f0327cb
Revises: d9633630e93a
Create Date: 2024-01-15 23:19:24.427425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8c8f0327cb'
down_revision: Union[str, None] = 'd9633630e93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using="lpad(CAST(student_id AS text), 12, '0')")
    op.create_index(op.f('ix_contest_problem_problem_id'), 'contest_problem', ['problem_id'], unique=False)
    op.alter_column('realname_reference', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using="lpad(CAST(student_id AS text), 12, '0')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realname_reference', 'student_id',
               existing_type=sa.Text(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               postgresql_using="CAST(student_id AS bigint)")
    op.drop_index(op.f('ix_contest_problem_problem_id'), table_name='contest_problem')
    op.alter_column('account', 'student_id',
               existing_type=sa.Text(),
               type_=sa.BIGINT(),
               existing_nullable=True,
               postgresql_using="CAST(student_id AS bigint)")
    # ### end Alembic commands ###
