"""require more not null

Revision ID: 7f6aac0ee84e
Revises: 4b07f60dfcfe
Create Date: 2024-01-22 19:56:36.944276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f6aac0ee84e'
down_revision: Union[str, None] = '4b07f60dfcfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE account SET student_id = '' WHERE student_id IS NULL;")
    op.execute("UPDATE problem SET title = '' WHERE title IS NULL;")
    op.execute("UPDATE judge_record_v1 SET code = '' WHERE code IS NULL;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('account', 'student_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('account', 'friendly_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('account', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('account', 'privilege',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('account', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contest', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('contest', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contest', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contest', 'type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contest', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('contest', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_contest_player_contest_id'), 'contest_player', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_player_username'), 'contest_player', ['username'], unique=False)
    op.alter_column('discussion', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('discussion', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('discussion', 'data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('discussion', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discussion', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_discussion_problem_id'), 'discussion', ['problem_id'], unique=False)
    op.create_index(op.f('ix_discussion_username'), 'discussion', ['username'], unique=False)
    op.alter_column('judge_record_v1', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_record_v1', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_record_v1', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('judge_record_v1', 'language',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('judge_record_v1', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('judge_record_v1', 'score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_record_v1', 'time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('judge_record_v1', 'time_msecs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_record_v1', 'memory_kbytes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_record_v1', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_judge_record_v1_problem_id'), 'judge_record_v1', ['problem_id'], unique=False)
    op.alter_column('judge_record_v2', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('judge_record_v2', 'language',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_record_v2', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_record_v2', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('judge_record_v2', 'status',
               existing_type=postgresql.ENUM('pending', 'compiling', 'judging', 'void', 'aborted', 'compile_error', 'runtime_error', 'time_limit_exceeded', 'memory_limit_exceeded', 'disk_limit_exceeded', 'memory_leak', 'wrong_answer', 'skipped', 'system_error', 'unknown_error', 'accepted', name='judgestatus'),
               nullable=False)
    op.alter_column('judge_record_v2', 'score',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('judge_record_v2', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_record_v2', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_judge_record_v2_problem_id'), 'judge_record_v2', ['problem_id'], unique=False)
    op.alter_column('judge_runner_v2', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_runner_v2', 'hardware',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_runner_v2', 'provider',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_runner_v2', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('judge_runner_v2', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_runner_v2', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_server_v1', 'base_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_server_v1', 'secret_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_server_v1', 'last_seen',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('judge_server_v1', 'busy',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('judge_server_v1', 'current_task',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_server_v1', 'friendly_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('judge_server_v1', 'detail',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('problem', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('problem', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('problem', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('realname_reference', 'student_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('realname_reference', 'real_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('realname_reference', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('realname_reference', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realname_reference', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('realname_reference', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('realname_reference', 'real_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('realname_reference', 'student_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('problem', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('problem', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('problem', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_server_v1', 'detail',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_server_v1', 'friendly_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_server_v1', 'current_task',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_server_v1', 'busy',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('judge_server_v1', 'last_seen',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('judge_server_v1', 'secret_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_server_v1', 'base_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_runner_v2', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_runner_v2', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_runner_v2', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('judge_runner_v2', 'provider',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_runner_v2', 'hardware',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_runner_v2', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_judge_record_v2_problem_id'), table_name='judge_record_v2')
    op.alter_column('judge_record_v2', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_record_v2', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('judge_record_v2', 'score',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('judge_record_v2', 'status',
               existing_type=postgresql.ENUM('pending', 'compiling', 'judging', 'void', 'aborted', 'compile_error', 'runtime_error', 'time_limit_exceeded', 'memory_limit_exceeded', 'disk_limit_exceeded', 'memory_leak', 'wrong_answer', 'skipped', 'system_error', 'unknown_error', 'accepted', name='judgestatus'),
               nullable=True)
    op.alter_column('judge_record_v2', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('judge_record_v2', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_record_v2', 'language',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_record_v2', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_judge_record_v1_problem_id'), table_name='judge_record_v1')
    op.alter_column('judge_record_v1', 'public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('judge_record_v1', 'memory_kbytes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_record_v1', 'time_msecs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_record_v1', 'time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('judge_record_v1', 'score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('judge_record_v1', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('judge_record_v1', 'language',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('judge_record_v1', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('judge_record_v1', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('judge_record_v1', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_discussion_username'), table_name='discussion')
    op.drop_index(op.f('ix_discussion_problem_id'), table_name='discussion')
    op.alter_column('discussion', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discussion', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discussion', 'data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('discussion', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('discussion', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_contest_player_username'), table_name='contest_player')
    op.drop_index(op.f('ix_contest_player_contest_id'), table_name='contest_player')
    op.alter_column('contest', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contest', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contest', 'type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contest', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contest', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contest', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('account', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('account', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('account', 'privilege',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('account', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('account', 'friendly_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('account', 'student_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('account', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
