"""add allow public submissions to problem

Revision ID: 971d49f56617
Revises: 2639b12746e6
Create Date: 2024-02-04 13:37:56.367972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971d49f56617'
down_revision: Union[str, None] = '2639b12746e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('allow_public_submissions', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'allow_public_submissions')
    # ### end Alembic commands ###
