"""add examples field in problem

Revision ID: 6d43b30e1d3d
Revises: 84a90187fc30
Create Date: 2024-09-26 20:16:00.097352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d43b30e1d3d'
down_revision: Union[str, None] = '84a90187fc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('examples', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'examples')
    # ### end Alembic commands ###
