"""add ignored_course_ids on user

Revision ID: 41839ff4b9c0
Revises: 6bb15e6bb28a
Create Date: 2024-02-13 16:14:24.561608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41839ff4b9c0'
down_revision: Union[str, None] = '6bb15e6bb28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ignored_course_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ignored_course_ids')
    # ### end Alembic commands ###
