"""add late submission

Revision ID: 84a90187fc30
Revises: 09e213667132
Create Date: 2024-09-20 20:31:52.674563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '84a90187fc30'
down_revision: Union[str, None] = '09e213667132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('late_submission_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'late_submission_deadline')
    # ### end Alembic commands ###
