"""add homework requirement fields

Revision ID: 4ca6c888463b
Revises: cd4339e8dce3
Create Date: 2024-01-30 21:18:43.527872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca6c888463b'
down_revision: Union[str, None] = 'cd4339e8dce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contest_group_contest_id', table_name='contest_group')
    op.drop_index('ix_contest_group_group_id', table_name='contest_group')
    op.drop_table('contest_group')
    op.add_column('contest', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('contest', sa.Column('course_id', sa.Integer(), nullable=True))
    op.execute('UPDATE contest SET course_id = (SELECT course.id FROM course ORDER BY course.id ASC LIMIT 1);')
    op.alter_column('contest', 'course_id', nullable=False)
    op.add_column('contest', sa.Column('group_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('contest', sa.Column('completion_criteria', sa.Integer(), nullable=True))
    op.add_column('contest', sa.Column('allowed_languages', sa.ARRAY(sa.Text()), nullable=True))
    op.create_index(op.f('ix_contest_course_id'), 'contest', ['course_id'], unique=False)
    op.create_foreign_key(None, 'contest', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contest_course_id_fkey', 'contest', type_='foreignkey')
    op.drop_index(op.f('ix_contest_course_id'), table_name='contest')
    op.drop_column('contest', 'allowed_languages')
    op.drop_column('contest', 'completion_criteria')
    op.drop_column('contest', 'group_ids')
    op.drop_column('contest', 'course_id')
    op.drop_column('contest', 'description')
    op.create_table('contest_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name='contest_group_contest_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='contest_group_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contest_group_pkey')
    )
    op.create_index('ix_contest_group_group_id', 'contest_group', ['group_id'], unique=False)
    op.create_index('ix_contest_group_contest_id', 'contest_group', ['contest_id'], unique=False)
    # ### end Alembic commands ###
