"""create index on lower(username)

Revision ID: d9633630e93a
Revises: 4d92921b834b
Create Date: 2024-01-15 22:59:41.498113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9633630e93a'
down_revision: Union[str, None] = '4d92921b834b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('username_lower', sa.Text(), sa.Computed('lower(username)', ), nullable=True))
    op.create_unique_constraint(None, 'account', ['username_lower'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'username_lower')
    # ### end Alembic commands ###
