"""use on delete cascade for realname reference and contest

Revision ID: 0245b59b53b9
Revises: df1925c72acc
Create Date: 2024-02-01 10:14:50.662855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0245b59b53b9'
down_revision: Union[str, None] = 'df1925c72acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contest_player_contest_id_fkey', 'contest_player', type_='foreignkey')
    op.create_foreign_key(None, 'contest_player', 'contest', ['contest_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('contest_problem_contest_id_fkey', 'contest_problem', type_='foreignkey')
    op.create_foreign_key(None, 'contest_problem', 'contest', ['contest_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_group_course_id_name', 'group', ['course_id', 'name'], unique=True)
    op.drop_constraint('group_realname_reference_group_id_fkey', 'group_realname_reference', type_='foreignkey')
    op.drop_constraint('group_realname_reference_realname_reference_id_fkey', 'group_realname_reference', type_='foreignkey')
    op.create_foreign_key(None, 'group_realname_reference', 'realname_reference', ['realname_reference_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_realname_reference', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_realname_reference_realname_reference_id_fkey', 'group_realname_reference', type_='foreignkey')
    op.drop_constraint('group_realname_reference_group_id_fkey', 'group_realname_reference', type_='foreignkey')
    op.create_foreign_key('group_realname_reference_realname_reference_id_fkey', 'group_realname_reference', 'realname_reference', ['realname_reference_id'], ['id'])
    op.create_foreign_key('group_realname_reference_group_id_fkey', 'group_realname_reference', 'group', ['group_id'], ['id'])
    op.drop_index('ix_group_course_id_name', table_name='group')
    op.drop_constraint('contest_problem_contest_id_fkey', 'contest_problem', type_='foreignkey')
    op.create_foreign_key('contest_problem_contest_id_fkey', 'contest_problem', 'contest', ['contest_id'], ['id'])
    op.drop_constraint('contest_player_contest_id_fkey', 'contest_player', type_='foreignkey')
    op.create_foreign_key('contest_player_contest_id_fkey', 'contest_player', 'contest', ['contest_id'], ['id'])
    # ### end Alembic commands ###
