"""add languages accepted to problem

Revision ID: 4b07f60dfcfe
Revises: 12a5cd563e99
Create Date: 2024-01-18 10:55:31.017101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b07f60dfcfe'
down_revision: Union[str, None] = '12a5cd563e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('languages_accepted', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'languages_accepted')
    # ### end Alembic commands ###
