"""add visibility control to judge runners

Revision ID: 4d92921b834b
Revises: 02d53b659c7c
Create Date: 2024-01-01 10:51:36.114038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d92921b834b'
down_revision: Union[str, None] = '02d53b659c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge_runners2', sa.Column('visible', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judge_runners2', 'visible')
    # ### end Alembic commands ###
