"""rename account to user

Revision ID: 08bbf757f96b
Revises: 7f6aac0ee84e
Create Date: 2024-01-29 09:16:28.859493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bbf757f96b'
down_revision: Union[str, None] = '7f6aac0ee84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('account', 'user')
    # ### end Alembic commands ###
    op.execute('ALTER SEQUENCE account_id_seq RENAME TO user_id_seq;')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT account_pkey TO user_pkey;')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT account_username_key TO user_username_key;')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT account_username_lower_key TO user_username_lower_key;')


def downgrade() -> None:
    op.execute('ALTER SEQUENCE user_id_seq RENAME TO account_id_seq;')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT user_pkey TO account_pkey;')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT user_username_key TO account_username_key;')
    op.execute('ALTER TABLE "user" RENAME CONSTRAINT user_username_lower_key TO account_username_lower_key;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'account')
    # ### end Alembic commands ###
