"""add finer-grained completion criteria

Revision ID: 6151a5e02041
Revises: ae57b081a531
Create Date: 2024-02-23 10:15:52.135328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6151a5e02041'
down_revision: Union[str, None] = 'ae57b081a531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('none', 'simple', 'python', name='completioncriteriatype').create(op.get_bind())
    op.add_column('contest', sa.Column('completion_criteria_type', sa.Enum('none', 'simple', 'python', name='completioncriteriatype'), server_default='none', nullable=False))
    op.alter_column('contest', 'completion_criteria',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True,
               postgresql_using="CAST(completion_criteria AS text)")
    op.execute('''UPDATE contest SET completion_criteria_type = 'simple' WHERE completion_criteria IS NOT NULL;''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''UPDATE contest SET completion_criteria = NULL WHERE completion_criteria_type != 'simple';''')
    op.alter_column('contest', 'completion_criteria',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using="CAST(completion_criteria AS integer)")
    op.drop_column('contest', 'completion_criteria_type')
    op.execute('DROP TYPE completioncriteriatype;')
    # ### end Alembic commands ###
