"""add show score on contest

Revision ID: 2b1992ab131b
Revises: 6151a5e02041
Create Date: 2024-04-26 22:09:47.745176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1992ab131b'
down_revision: Union[str, None] = '6151a5e02041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('show_score', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'show_score')
    # ### end Alembic commands ###
