"""add apps and access tokens

Revision ID: 09e213667132
Revises: 6151a5e02041
Create Date: 2024-08-12 17:35:50.254643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '09e213667132'
down_revision: Union[str, None] = '6151a5e02041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_app_client_id'), 'oauth_app', ['client_id'], unique=False)
    op.create_table('access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['oauth_app.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_token_app_id'), 'access_token', ['app_id'], unique=False)
    op.create_index(op.f('ix_access_token_token'), 'access_token', ['token'], unique=False)
    op.create_index(op.f('ix_access_token_user_id'), 'access_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_token_user_id'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_token'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_app_id'), table_name='access_token')
    op.drop_table('access_token')
    op.drop_index(op.f('ix_oauth_app_client_id'), table_name='oauth_app')
    op.drop_table('oauth_app')
    # ### end Alembic commands ###
