"""add problem attachments

Revision ID: 3213760f84d3
Revises: 5f5ce14c214d
Create Date: 2025-04-10 16:03:37.180069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3213760f84d3'
down_revision: Union[str, None] = '5f5ce14c214d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_attachment_name'), 'problem_attachment', ['name'], unique=False)
    op.create_index(op.f('ix_problem_attachment_problem_id'), 'problem_attachment', ['problem_id'], unique=False)
    op.create_index('ix_problem_attachment_problem_id_name', 'problem_attachment', ['problem_id', 'name'], unique=True)
    op.create_index(op.f('ix_problem_attachment_user_id'), 'problem_attachment', ['user_id'], unique=False)
    op.add_column('course', sa.Column('attachment_quota_bytes', sa.Integer(), server_default='1073741824', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'attachment_quota_bytes')
    op.drop_index(op.f('ix_problem_attachment_user_id'), table_name='problem_attachment')
    op.drop_index('ix_problem_attachment_problem_id_name', table_name='problem_attachment')
    op.drop_index(op.f('ix_problem_attachment_problem_id'), table_name='problem_attachment')
    op.drop_index(op.f('ix_problem_attachment_name'), table_name='problem_attachment')
    op.drop_table('problem_attachment')
    # ### end Alembic commands ###
